// src/ui/sampleDataAi.ts
// TASK-006 — AI-driven sample data generator.
//
// Spec (docs/AI_HANDOFF/tasks/TASK-006.md):
//   - values generated by AI work model from column-name semantics
//   - id_<table> + created_at + identity/nextval columns never inserted
//   - INSERT-only-for-this-table whitelist validation (all-or-nothing)
//   - one adapter.runQuery call (multi-statement, implicit transaction)
//   - summary toast
//
// Pure functions + aiGenerateSampleData orchestrator. No vscode imports
// (orchestrator takes `showInfo`/`showError` callbacks so tests can stub).

import type { AiConfig } from "../ai/settings";
import type { ConnectionConfig } from "../config/types";
import type { DbAdapter } from "../adapters/types";
import type { ProviderRequest, ProviderResult } from "../ai/provider";
import { splitStatements } from "../core/statementParser";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface SampleColumn {
  name: string;
  type: string;
  nullable: boolean;
  default?: string | null;
}

export interface AiGenerateSampleDataDeps {
  cfg: AiConfig;
  conn: ConnectionConfig;
  schema: string;
  table: string;
  n: number;
  /** Already filtered insertable columns (caller ran pickInsertableColumns). */
  columns: SampleColumn[];
  complete: (req: ProviderRequest) => Promise<ProviderResult>;
  getAdapterFor: () => Promise<DbAdapter>;
  showInfo: (msg: string) => void;
  showError?: (msg: string) => void;
}

export type ParseResult =
  | { ok: true; statements: string[] }
  | { ok: false; reason: string };

// ---------------------------------------------------------------------------
// buildSampleDataPrompt
// ---------------------------------------------------------------------------

/**
 * Build the prompt sent to the work model. Lists insertable columns with
 * types + nullability and asks for exactly `n` INSERT statements against
 * `schema.table`. Forbids markdown / explanatory text.
 */
export function buildSampleDataPrompt(
  schema: string,
  table: string,
  columns: SampleColumn[],
  n: number,
): string {
  const qSchema = `"${schema.replace(/"/g, '""')}"`;
  const qTable = `"${table.replace(/"/g, '""')}"`;
  const target = `${qSchema}.${qTable}`;
  const colsList = columns
    .map((c, idx) => {
      const nullability = c.nullable ? "NULL" : "NOT NULL";
      return `  ${idx + 1}. ${c.name} (${c.type}, ${nullability})`;
    })
    .join("\n");
  return [
    `You generate realistic PostgreSQL sample data.`,
    `Target table: ${target}`,
    `Insertable columns (in this order):`,
    colsList,
    ``,
    `Output exactly ${n} INSERT statements, each like:`,
    `  INSERT INTO ${target} ("col1","col2") VALUES ('v1','v2');`,
    ``,
    `Rules:`,
    `- Plain SQL only, no markdown fences, no backticks, no explanation.`,
    `- Use single-quoted string literals; escape single quotes as ''.`,
    `- All values must be valid PostgreSQL literals for the column type.`,
    `- Do not include columns not listed above.`,
    `- Do not wrap the output in a code block.`,
    `- Do not add commentary before or after the statements.`,
    ``,
    `Produce exactly ${n} INSERT statements now.`,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// pickInsertableColumns
// ---------------------------------------------------------------------------

/**
 * Drop columns that should not be inserted:
 *   - id_<table> / ID_<TABLE> (case-insensitive)
 *   - created_at / CREATED_AT (case-insensitive)
 *   - any column whose default expression contains `nextval`
 *     (identity / sequence-driven columns)
 */
export function pickInsertableColumns(
  tableName: string,
  columns: SampleColumn[],
): SampleColumn[] {
  const idToken = `id_${tableName}`.toLowerCase();
  return columns.filter((c) => {
    if (c.name.toLowerCase() === idToken) return false;
    if (c.name.toLowerCase() === "created_at") return false;
    if (typeof c.default === "string" && /nextval/i.test(c.default)) {
      return false;
    }
    return true;
  });
}

// ---------------------------------------------------------------------------
// parseInsertStatements
// ---------------------------------------------------------------------------

/**
 * Whitelist: every non-empty statement must be
 *   INSERT INTO <target> ...
 * where target is `schema.table` either quoted ("s"."t") or bare (s.t).
 * Statements containing DDL/DML other than that INSERT pattern → reject.
 */
export function parseInsertStatements(
  text: string,
  schema: string,
  table: string,
): ParseResult {
  const esc = (s: string): string => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const qSchema = `"${schema.replace(/"/g, '""')}"`;
  const qTable = `"${table.replace(/"/g, '""')}"`;
  const bareTarget = `${esc(schema)}\\.${esc(table)}`;
  // Use lookahead after the target (instead of \b) because the closing
  // double-quote of "table" is a non-word char; \b compares the closing
  // quote against the next char (also non-word) and never matches.
  const insertPattern = new RegExp(
    `^\\s*INSERT\\s+INTO\\s+(?:${qSchema}\\.${qTable}|${bareTarget})(?=[\\s(;]|$)`,
    "i",
  );
  const parsed = splitStatements(text);
   const out: string[] = [];
  for (const stmt of parsed) {
    const sql = stmt.text.replace(/;\s*$/, "").trim();
    if (sql.length === 0) continue;
    if (!insertPattern.test(sql)) {
      return { ok: false, reason: `Non-INSERT or wrong-table statement: ${sql.slice(0, 80)}` };
    }
    out.push(sql);
  }
  if (out.length === 0) {
    return { ok: false, reason: "No INSERT statements parsed" };
  }
  return { ok: true, statements: out };
}

// ---------------------------------------------------------------------------
// aiGenerateSampleData
// ---------------------------------------------------------------------------

/**
 * Orchestrator. Caller passes already-picked insertable columns + the deps
 * needed to run the model and execute. Returns the count of INSERTs joined
 * and submitted via a single adapter.runQuery call (implicit transaction).
 *
 * Failure modes (all reject with a user-showable message):
 *   - empty insertable columns → info "nothing to insert" + returns {inserted:0}
 *   - parse failure → error + ZERO partial insert (runQuery never called)
 *   - adapter failure → error rethrown
 */
export async function aiGenerateSampleData(
  deps: AiGenerateSampleDataDeps,
): Promise<{ inserted: number }> {
  const {
    cfg,
    schema,
    table,
    n,
    columns,
    complete,
    getAdapterFor,
    showInfo,
    showError,
  } = deps;

  if (columns.length === 0 || n <= 0) {
    showInfo(`VSDB: nothing to insert into ${schema}.${table}`);
    return { inserted: 0 };
  }

  const prompt = buildSampleDataPrompt(schema, table, columns, n);
  const req: ProviderRequest = {
    modelId: cfg.models.work.modelId,
    messages: [{ role: "user", content: prompt }],
    temperature: 0.7,
  };
  const result = await complete(req);

  const parsed = parseInsertStatements(result.text, schema, table);
  if (!parsed.ok) {
    const msg = `AI output rejected: ${parsed.reason}`;
    if (showError) showError(`Generate Sample Data failed: ${msg}`);
    throw new Error(msg);
  }

  // Single multi-statement run → implicit transaction (all-or-nothing).
  const joined = parsed.statements.join("\n");
  const adapter = await getAdapterFor();
  await adapter.runQuery(joined);

  showInfo(`VSDB: inserted ${parsed.statements.length} sample rows into ${schema}.${table}`);
  return { inserted: parsed.statements.length };
}
