// src/extensionConfigExport.ts — Cycle AD TASK-003
//
// OMP config injection layer. Pure emit (`emitVsdbAiConfig`) is webview-
// importable (no `vscode` import in the pure path); the host-only
// `writeVsdbAiConfig` is the vscode-bound shim that writes the YAML +
// markdown to the workspace folder and returns absolute paths plus a
// copy-pasteable `omp` command line.
//
// Privacy contract (cycle AD §9): the apiKey NEVER appears in the YAML or
// the command line. We emit an env-var hint comment so OMP picks the key
// up from the user's `OPENAI_API_KEY` (and `OPENAI_BASE_URL`) at runtime.
import type { AiSettings } from "./ai/settings";
import type { ChatMessage } from "./ai/provider";
import type { AdapterFactory } from "./ai/tools/types";
import { formatSystemPrompt } from "./ui/aiChatPanel";

/** Build the OMP-friendly YAML overlay + suggested command line.
 *
 * The YAML is what `omp --config <path>` will load as an overlay over
 * `~/.omp/config.yml`. We use keys OMP understands:
 *   - `model.default` / `model.reasoning` — mapped to the user's
 *     `models.work` / `models.smart` ids (omp's `--model` flag prefers
 *     these per role).
 *   - `appendSystemPrompt.file` — the markdown file we just wrote.
 *   - `openai` block — base URL only; apiKey is left as a comment that
 *     names the env var OMP picks up automatically (`OPENAI_API_KEY`).
 *
 * The command line is copy-pasteable as-is:
 *   `omp --config <absConfigPath> -p "<prompt>" --append-system-prompt <absContextPath> --model <workModelId>`
 *
 * `factory` + `history` are passed through to `formatSystemPrompt` so the
 * generated `dbContextMd` markdown uses the same byte content the chat
 * runtime would inject as a system prompt (cycle AD §8).
 */
export function emitVsdbAiConfig(
  settings: AiSettings,
  contextPath: string,
  configPath: string,
  factory: AdapterFactory,
  history: readonly ChatMessage[],
): {
  yaml: string;
  ompCommandLine: string;
  dbContextMd: Promise<string>;
} {
  const yaml = renderYaml(settings, contextPath);
  const ompCommandLine = renderCommandLine(settings, contextPath, configPath);
  // DRY seam (cycle AD §8) — chat runtime + OMP exporter produce identical
  // content for identical input. The Promise defers the awaited adapter
  // calls until the caller awaits `dbContextMd`.
  const dbContextMd = formatSystemPrompt(factory, history, {});
  return { yaml, ompCommandLine, dbContextMd };
}

/** YAML emitter — pure, side-effect-free. The `openai` block emits
 * baseUrl only; apiKey is intentionally absent (cycle AD §9 privacy
 * lock). The `# apiKey: $OPENAI_API_KEY` comment is a hint to the user
 * who reads the YAML — never a value. */
function renderYaml(settings: AiSettings, contextPath: string): string {
  const baseUrl = settings.baseUrl.trim();
  const workModel = settings.models.work.modelId.trim();
  const smartModel = settings.models.smart.modelId.trim();
  const lines: string[] = [
    "# Generated by VSDB — `vsdb.ai.useWithOmp` command.",
    "# Overlay over ~/.omp/config.yml. Edit freely; re-run the command to refresh.",
    "",
    "provider: openai",
    "",
    "model:",
    `  default: ${yamlString(workModel)}`,
    `  reasoning: ${yamlString(smartModel)}`,
    "",
    "openai:",
    `  baseURL: ${yamlString(baseUrl)}`,
    "  # apiKey: $OPENAI_API_KEY   # set OPENAI_API_KEY in your shell; OMP picks it up automatically",
    "",
    "appendSystemPrompt:",
    `  file: ${yamlString(contextPath)}`,
    "",
  ];
  return lines.join("\n");
}

/** Quote a YAML string scalar. Avoids producing strings that look like
 * booleans / numbers / null. */
function yamlString(value: string): string {
  // Always double-quote; escape backslashes + double-quotes; newlines are
  // impossible in model ids / URLs but we handle defensively.
  const escaped = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
  return `"${escaped}"`;
}

/** Build the copy-pasteable `omp` command line.
 * Order: --config <path> -p "<prompt>" --append-system-prompt <path>
 * --model <workModelId>. */
function renderCommandLine(
  settings: AiSettings,
  contextPath: string,
  configPath: string,
): string {
  const workModel = settings.models.work.modelId.trim();
  return [
    "omp",
    `--config "${configPath}"`,
    `-p "Use the VSDB schema context to help me with my database question."`,
    `--append-system-prompt "${contextPath}"`,
    `--model "${workModel}"`,
  ].join(" ");
}
// ----- vscode-bound host shim ----------------------------------------------
// Keep this block at the bottom so the pure emitter above remains the first
// 100-or-so lines reviewers read. The shim is the only place that imports
// `vscode` directly; everything else stays webview-friendly.

/** Absolute path of the OMP config YAML written into the workspace's
 * `.vscode` folder. */
const OMP_CONFIG_FILENAME = "vsdb-ai-config.yml";
/** Absolute path of the DB-context markdown file (the appended system
 * prompt OMP will load with `--append-system-prompt`). */
const DB_CONTEXT_FILENAME = "vsdb-db-context.md";

/** Empty-when-absent helper used by `writeVsdbAiConfig` when no DB
 * connection is active. We still write a placeholder so `omp` has a file
 * to point at; the placeholder explains how to load a connection. */
const NO_CONNECTION_MARKER =
  "# No active VSDB connection — open the VSDB panel and pick one, then re-run vsdb.ai.useWithOmp.\n" +
  "# Once a connection is active, this file is rewritten with the schema DDL.\n";

/** Result envelope returned by `writeVsdbAiConfig`. */
export interface WriteVsdbAiConfigResult {
  configPath: string;
  contextPath: string;
  ompCommandLine: string;
}

/** Vscode-bound host shim: write the OMP YAML overlay + DB context markdown
 * into the workspace folder's `.vscode/` directory, then return absolute
 * paths and the copy-pasteable `omp` command line. The apiKey is NEVER
 * written to disk — we read it from SecretStorage only to verify presence
 * (so we can warn the user when nothing is configured), then drop it. */
export async function writeVsdbAiConfig(
  folder: import("vscode").WorkspaceFolder,
  settings: AiSettings,
  factory: AdapterFactory,
  history: readonly ChatMessage[],
): Promise<WriteVsdbAiConfigResult> {
  // vscode is dynamically imported inside this function so the pure
 // emitter above stays webview-importable. The shim is only ever called
 // from extension.ts activation (host-only).
  const vscode = await import("vscode");
  const folderUri = folder.uri;
  const vscodeDir = vscode.Uri.joinPath(folderUri, ".vscode");
  const configUri = vscode.Uri.joinPath(vscodeDir, OMP_CONFIG_FILENAME);
  const contextUri = vscode.Uri.joinPath(vscodeDir, DB_CONTEXT_FILENAME);
  const configPath = configUri.fsPath;
  const contextPath = contextUri.fsPath;

  // Ensure `.vscode/` exists. Workspace folders that are read-only or
  // already have a `.vscode/` from another tool still pass through — the
  // createDirectory call is idempotent.
  try {
    await vscode.workspace.fs.createDirectory(vscodeDir);
  } catch {
    // Directory may already exist; createDirectory throws "already exists"
    // which we treat as success. Any other failure surfaces when we try
    // to write the file below.
  }

  // Build the DB context markdown via the same `formatSystemPrompt` the
 // chat runtime uses (cycle AD §8 byte-equality pin). On introspection
 // failure we fall back to the placeholder marker so the file is always
 // present and `omp --append-system-prompt` has a valid target.
  let dbContextMd: string;
  try {
    dbContextMd = await formatSystemPrompt(factory, history, {});
  } catch {
    dbContextMd = NO_CONNECTION_MARKER;
  }

  const { yaml, ompCommandLine } = emitVsdbAiConfigRaw(settings, contextPath, configPath);

  // Write both files atomically (VS Code's workspace.fs.writeFile is
 // already overwrite-or-create; we just rely on it).
  await vscode.workspace.fs.writeFile(configUri, new TextEncoder().encode(yaml));
  await vscode.workspace.fs.writeFile(contextUri, new TextEncoder().encode(dbContextMd));

  return { configPath, contextPath, ompCommandLine };
}

/** Synchronous YAML + command-line emitter used by `writeVsdbAiConfig`.
 * Kept separate from `emitVsdbAiConfig` because the latter returns a
 * Promise for the DB context markdown (which we await in the host shim
 * before writing the file). */
function emitVsdbAiConfigRaw(
  settings: AiSettings,
  contextPath: string,
  configPath: string,
): { yaml: string; ompCommandLine: string } {
  return {
    yaml: renderYamlPublic(settings, contextPath),
    ompCommandLine: renderCommandLinePublic(settings, contextPath, configPath),
  };
}

// Re-export the internal helpers so `writeVsdbAiConfig` can reach them
// without leaking implementation outside the module.
function renderYamlPublic(settings: AiSettings, contextPath: string): string {
  return renderYaml(settings, contextPath);
}

function renderCommandLinePublic(
  settings: AiSettings,
  contextPath: string,
  configPath: string,
): string {
  return renderCommandLine(settings, contextPath, configPath);
}
